export const PRODUCTS_GET_PRODUCTS_LIST = 'PRODUCTS_GET_PRODUCTS_LIST'
export const PRODUCTS_GET_PRODUCTS_LIST_SUCCESS =
  'PRODUCTS_GET_PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_GET_PRODUCTS_LIST_FAILURE =
  'PRODUCTS_GET_PRODUCTS_LIST_FAILURE'
export const ADD_PRODUCT_TO_SHOPPING_CART = 'ADD_PRODUCT_TO_SHOPPING_CART'
export const REMOVE_PRODUCT_FROM_SHOPPING_CART =
  'REMOVE_PRODUCT_FROM_SHOPPING_CART'
