export const PRODUCTS_GET_PRODUCTS_LIST = 'PRODUCTS_GET_PRODUCTS_LIST'
export const PRODUCTS_GET_PRODUCTS_LIST_SUCCESS =
  'PRODUCTS_GET_PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_GET_PRODUCTS_LIST_FAILURE =
  'PRODUCTS_GET_PRODUCTS_LIST_FAILURE'
