export const PRODUCTS_GET_PRODUCTS_LIST = 'PRODUCTS_GET_PRODUCTS_LIST'
export const PRODUCTS_GET_PRODUCTS_LIST_SUCCESS =
  'PRODUCTS_GET_PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_GET_PRODUCTS_LIST_FAILURE =
  'PRODUCTS_GET_PRODUCTS_LIST_FAILURE'
export const ADD_PRODUCT_TO_SHOPPING_CART = 'ADD_PRODUCT_TO_SHOPPING_CART'
export const REMOVE_PRODUCT_FROM_SHOPPING_CART =
  'REMOVE_PRODUCT_FROM_SHOPPING_CART'
export const USER_CREATE_NEW_USER = 'USER_CREATE_NEW_USER'
export const USER_CREATE_NEW_USER_SUCCESS = 'USER_CREATE_NEW_USER_SUCCESS'
export const USER_CREATE_NEW_USER_FAILURE = 'USER_CREATE_NEW_USER_FAILURE'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES'
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS'
export const GET_PRODUCT_CATEGORIES_FAILURE = 'GET_PRODUCT_CATEGORIES_FAILURE'
export const SET_MODAL_VISIBILITY_STATE_FOR_PRODUCT_DETAIL =
  'SET_MODAL_VISIBILITY_STATE_FOR_PRODUCT_DETAIL'
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS'
